#!/bin/bash
#
#======= HEADER ===========

set -e

BUILDDIR=~/src/macports/SynfigStudio-app
MACPORTS=/tmp/skl/SynfigStudio.app/Contents/Resources

export SCRIPTPATH=`dirname "$0"`
bash "${SCRIPTPATH}/1-link-prep"

export PATH="$MACPORTS/bin:$MACPORTS/sbin:$PATH"
export SYNFIG_ROOT=${MACPORTS}/
export SYNFIG_MODULE_LIST=${MACPORTS}/etc/synfig_modules.cfg
export MACOSX_DEPLOYMENT_TARGET=10.5

#======= HEADER END ===========

#We should do that, otherwise python won't build:
if [ ! -e /Applications/MacPorts ]; then
   echo "Backing up /Applications/MacPorts dir..."
   mv /Applications/MacPorts /Applications/MacPorts.bak
fi

compile_synfig()
{

port selfupdate

port install synfigstudio || true
#synfig -q installer_logo.sif -o installer_logo.png --time 0
#synfig(294) [23:51:01] info: Loading modules from /tmp/skl/#SynfigStudio.app/Contents/Resources/etc/synfig_modules.cfg
#synfig: warning: Unable to find module "mod_magickpp" (file not found)
#synfig: warning: Unable to find module "mod_libavcodec" (file not found)
#synfig(294) [23:51:01] error: Standard Exception: basic_string::_S_construct NULL not valid
#Unable to load 'installer_logo.sif'.
#Throwing out job...
#Nothing to do!

#Workaround:
[ ! -e ~/src/macports/synfig-build ] || rm -rf ~/src/macports/synfig-build
cd /tmp/skl/SynfigStudio.app/Contents/Resources/var/macports/build/
DIRPATH=`ls`
cd -
VERSION=`synfig --version 2>&1 | cut -d " " -f 2`
cp -R "/tmp/skl/SynfigStudio.app/Contents/Resources/var/macports/build/$DIRPATH/synfigstudio/work/synfigstudio-$VERSION" ~/src/macports/synfig-build
cd ~/src/macports/synfig-build/images
make
cd -
cp -R ~/src/macports/synfig-build/images/* "/tmp/skl/SynfigStudio.app/Contents/Resources/var/macports/build/$DIRPATH/synfigstudio/work/synfigstudio-$VERSION/images"

port install synfigstudio
}

# We need that to be sure that the MacPorts dir will be restored even when the compilation fail
if ( compile_synfig ); then
   EXITCODE=0
else
   EXITCODE=1
fi

#restore Applications/MacPorts dir
if [ -e /Applications/MacPorts.bak ]; then
	echo "Restoring /Applications/MacPorts dir."
	rm -rf /Applications/MacPorts
	mv /Applications/MacPorts.bak /Applications/MacPorts
fi

if [[ $EXITCODE == 0 ]]; then
	echo "Completed Succesfully."
else
	echo "Error."
fi

rm /tmp/skl/SynfigStudio.app

exit $EXITCODE
